# Generated by Django 3.2 on 2024-04-08 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20240406_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
